FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-openjdk:latest-buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN apt update \
    && apt upgrade -y

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
